# Model arguments
model_name_or_path: pretrained/Qwen2.5-Math-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: yentinglin/OpenR1-Math-220k-trl-format
dataset_configs:
- all
preprocessing_num_workers: 16

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: Qwen2.5-1.5B-Open-R1-Distill
# hub_strategy: every_save
learning_rate: 5.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: false
max_seq_length: 32768
max_steps: -1
num_train_epochs: 3
output_dir: results/Qwen2.5-Math-1.5B-OpenR1-220k
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
# push_to_hub: true
report_to:
- wandb
save_strategy: epoch
seed: 42
use_liger: true
warmup_ratio: 0.1